
FLAC:
  # FLAC files base directory. Must be absolute path.
  # directory: /mnt/zik/FLAC
  directory: /media/bleuarff/DIVERS/bfc

MP3:
  # MP3 files base directory. Must be absolute path.
  directory: /media/bleuarff/DIVERS/bfc

# flac: flac --picture="3||||{pathtopicture}"  --output-filename="{output path}" -3
